--------------------------------------------------------
--  Arquivo criado - Segunda-feira-Dezembro-04-2017   
--------------------------------------------------------
REM INSERTING into AMIZADE
SET DEFINE OFF;
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('3','1','4','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('18','1','11','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('19','1','12','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('20','1','15','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('22','0','3','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('12','1','7','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('7','1','16','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('21','1','13','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('13','1','2','1');
Insert into AMIZADE (ID,APROVADO,USUARIO_SOLICITADO_ID,USUARIO_SOLICITANTE_ID) values ('','','','');
